spring:
  application:
    name: server
  config:
    import: optional:application-secret.properties
  jpa:
    hibernate:
      ddl-auto: create # 실제 서버에서 사용시 모든 데이터가 다 날아가므로 주의
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true