spring:
  application:
    name: server
  config:
    import: optional:application-secret.properties
  jpa:
    hibernate:
      ddl-auto: none # 실제 서버에서 사용시 모든 데이터가 다 날아가므로 주의
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB

google:
  ai:
    credential: ${GOOGLE_AI_CREDENTIAL_PATH}
    key: ${GOOGLE_AI_KEY}
  storage:
    bucket-name: ${GOOGLE_BUCKET_NAME}

client.url: ${CLIENT_URL}
output-dir-root: ${OUTPUT_DIR_ROOT}

#logging.level.root: DEBUG