version: "3.8"

services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - ./arcane-bus-436701-d1-94e3c0514209.json:/app/arcane-bus-436701-d1-94e3c0514209.json
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg