CREATE TABLE member (
    id BIGINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMIN', 'USER') NULL
);

CREATE TABLE report (
    id BIGINT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    file_directory VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);